from typing import List, Literal, Optional
from pydantic import BaseModel, Field, StringConstraints, model_validator
from typing_extensions import Annotated
from datetime import datetime
from core.casing import camel_alias
from services.product_rules import validate_price_sale

ProductName = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=200)]
PublishValue = Literal["published", "draft"]

class CamelModel(BaseModel):
    model_config = {
        "alias_generator": camel_alias,
        "populate_by_name": True,
        "from_attributes": True,
    }

class Label(CamelModel):
    enabled: bool
    content: str

class RatingBucket(CamelModel):
    name: str
    star_count: int
    review_count: int

class Review(CamelModel):
    id: str
    name: str
    posted_at: datetime
    comment: str
    is_purchased: bool
    rating: float
    avatar_url: Optional[str] = None
    helpful: int
    attachments: List[str] = []

class ProductOut(CamelModel):
    id: str
    gender: List[str]
    images: List[str]
    reviews: List[Review]
    publish: str
    ratings: List[RatingBucket]
    category: str
    available: int
    price_sale: Optional[float] = None
    taxes: Optional[float] = None
    quantity: int
    inventory_type: Optional[str] = None
    tags: List[str]
    code: Optional[str] = None
    description: Optional[str] = None
    sku: Optional[str] = None
    created_at: datetime | str
    name: str
    price: float
    cover_url: Optional[str] = None
    colors: List[str]
    total_ratings: float
    total_sold: int
    total_reviews: int
    new_label: Label
    sale_label: Label
    sizes: List[str]
    sub_description: Optional[str] = None

class ProductCreate(CamelModel):
    # id is generated by the backend (UUID)
    name: ProductName
    category: str
    price: float = Field(ge=0)
    publish: PublishValue = "published"
    quantity: int = Field(default=0, ge=0)
    available: Optional[int] = Field(default=None, ge=0)  # defaults to quantity
    taxes: Optional[float] = Field(default=None, ge=0)
    price_sale: Optional[float] = None
    inventory_type: Optional[str] = None
    code: Optional[str] = None
    sku: Optional[str] = None
    description: Optional[str] = None  # HTML
    sub_description: Optional[str] = None
    cover_url: Optional[str] = None
    gender: List[str] = []
    tags: List[str] = []
    images: Optional[List] = None
    colors: List[str] = []
    sizes: List[str] = []

    @model_validator(mode="after")
    def _check(self):
        validate_price_sale(self.price, self.price_sale)
        if self.available is None:
            self.available = self.quantity
        return self


# Fields that may be cleared with an explicit null on update.
CLEARABLE_FIELDS = {
    "price_sale", "taxes", "inventory_type", "code", "sku",
    "description", "sub_description", "cover_url",
}


class ProductUpdate(CamelModel):
    # Partial PUT: only fields present in the body are applied (explicit null clears
    # the optional fields listed in CLEARABLE_FIELDS). total_sold / total_ratings /
    # total_reviews / reviews / ratings are server-managed and cannot be set here.
    name: Optional[ProductName] = None
    category: Optional[str] = None
    price: Optional[float] = Field(default=None, ge=0)
    publish: Optional[PublishValue] = None
    available: Optional[int] = Field(default=None, ge=0)
    quantity: Optional[int] = Field(default=None, ge=0)
    taxes: Optional[float] = Field(default=None, ge=0)
    price_sale: Optional[float] = None
    inventory_type: Optional[str] = None
    code: Optional[str] = None
    sku: Optional[str] = None
    description: Optional[str] = None
    sub_description: Optional[str] = None
    cover_url: Optional[str] = None
    gender: Optional[List[str]] = None
    tags: Optional[List[str]] = None
    # Desired remaining images (URLs or keys). Can only remove/reorder; use add_images to add.
    images: Optional[List[str]] = None
    colors: Optional[List[str]] = None
    sizes: Optional[List[str]] = None

    @model_validator(mode="after")
    def _check(self):
        for f in self.model_fields_set:
            if getattr(self, f) is None and f not in CLEARABLE_FIELDS:
                raise ValueError(f"{f} cannot be null")
        if "price" in self.model_fields_set and "price_sale" in self.model_fields_set:
            validate_price_sale(self.price, self.price_sale)
        return self


class ProductListOut(CamelModel):
    items: List[ProductOut]
    limit: int
    next_token: Optional[str] = Field(default=None, alias="nextToken")
